name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

        
    - name: Python - VENV - Poetry
  # You may pin to the exact commit or the version.
  # uses: DarylStark/actions-python-venv-poetry@a7b7c59338aedeaf29d647addebf2af14c16df22
  uses: DarylStark/actions-python-venv-poetry@v1
  with:
    # The version of Python to use.
    python-version: # optional, default is 3.12
    # They key to use for the caching of the VENV
    cache-key: # optional, default is python-venv-poetry-${{ hashFiles('./poetry.lock') }}
    # The groups of dependencies to install as comma seperated list.
    groups: # optional
          
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
